### ISSUE TITLE
Selecting element to which context menu is attached

### ISSUE THREAD

**Issue by michaelbilow** [jakiestfu/Context.js#24]
Hi!

First off, this tool's really great, thanks a lot for releasing it. I've attached the context menu to a class of elements in my code, and I want to access the element from which the context menu was raised. Is there a clean way to do it? I'm looking for something like the following:

```
context.attach(".my-class", [
{text: 'Act on right-clicked element', action: function(e){
            e.preventDefault();
                        // Is there a way to get a selector for the clicked item?
            }}]
```

**Comment by AchoArnold** [comment]
@chuyelchulo  Presently, there is no way to do that. There is [an issue for this](https://github.com/jakiestfu/Context.js/issues/7).

Checkout [this pull request](https://github.com/jakiestfu/Context.js/pull/14) which addresses this problem.

**Comment by michaelbilow** [comment]
Thanks @najela, that's really useful. I think I should be able to patch it myself based on that pull request.
